### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by 2600box** [NicoWeio/blinkist#2]
Hello, I get this error when trying to grab the free curated blinks?

```
Traceback (most recent call last):
  File "/root/blinkist/./main.py", line 121, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/blinkist/./main.py", line 113, in main
    download_book(
  File "/root/blinkist/./main.py", line 58, in download_book
    chapter.download_audio(book_dir)
  File "/root/blinkist/blinkist/chapter.py", line 33, in download_audio
    assert 'm4a' in self.data['signed_audio_url']
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by NicoWeio** [comment]
Should be fixed in 29c649c12f99b36f974165c6f1dcd028648e0968. Thanks for reporting!
