### ISSUE TITLE
--freedaily option the only one working

### ISSUE THREAD

**Issue by reverberator** [NicoWeio/blinkist#24]
Hi,

Maybe it is some web app update on cloudflare that is blocking everything else but --freedaily option?

I'm using the repo's latest code. I'm getting this error message when using --book-slug option:

`
E:\blinkist\software>python main.py --book-slug the-highly-sensitive-person-en e:\blinkist\resumenes
[11:17:52] INFO     Book: “The Highly Sensitive Person”                                                     main.py:189
[11:17:53] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:17:55] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:17:58] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:01] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:03] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:06] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:09] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:11] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:14] INFO     Retrying in 2.0 seconds…                                                               common.py:17
[11:18:16] ERROR    Error downloading “The Highly Sensitive Person”: RetryError[<Future at 0x17e4afbf940     main.py:83
                    state=finished raised CloudflareChallengeError>]
           WARNING  Renamed output directory to “the-highly-sensitive-person-en – ERROR”                     main.py:92
           CRITICAL Exiting…                                                                                 main.py:97
           CRITICAL Hint: Try using --continue-on-error.                                                     main.py:98
Fetching chapters… ⠦ ---------------------------------------- 0/4 -:--:--
Traceback (most recent call last):
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "E:\blinkist\software\blinkist\common.py", line 30, in request
    raise cloudscraper.exceptions.CloudflareChallengeError()
cloudscraper.exceptions.CloudflareChallengeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\blinkist\software\main.py", line 198, in <module>
    main()
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\blinkist\software\main.py", line 191, in main
    download_book(
  File "E:\blinkist\software\main.py", line 57, in download_book
    _ = book.chapters
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\functools.py", line 981, in __get__
    val = self.func(instance)
  File "E:\blinkist\software\blinkist\book.py", line 54, in chapters
    chapters = [
  File "E:\blinkist\software\blinkist\book.py", line 55, in <listcomp>
    Chapter.from_id(self, chapter['id'])
  File "E:\blinkist\software\blinkist\chapter.py", line 16, in from_id
    chapter_data = api_request_web(f'books/{book.id}/chapters/{chapter_id}')
  File "E:\blinkist\software\blinkist\common.py", line 52, in api_request_web
    return api_request('https://blinkist.com/api/', endpoint, params=params)
  File "E:\blinkist\software\blinkist\common.py", line 43, in api_request
    response = request(url, params=params, headers=HEADERS)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\sicon\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x17e4afbf940 state=finished raised CloudflareChallengeError>]`

**Comment by NicoWeio** [comment]
Thanks for reporting this! 
Due to the regular automated testing, I am already aware of the issue, but haven't had time to look into it yet. I'll update this issue accordingly, but it might take some weeks.

**Comment by NicoWeio** [comment]
There's still some testing to be done (app API, other endpoints, …), but it looks to me like Blinkist now actually requires Blinkist Premium for non-free content. I've updated the repo accordingly.
If you have Premium and are using Firefox (or willing to play with the code), you can try the https://github.com/NicoWeio/blinkist/tree/feature/import-session branch to regain access to all content.

**Comment by reverberator** [comment]
Hi, how are you? I don't have a premium account, so I won't be able to try the updates.

I really like this app, best regards.

**Comment by pranavmalikk** [comment]
hey @NicoWeio i tried downloading using your book-slug method with premium account on firefox, yet i'm getting:
[23:05:47] INFO     Book: “Get Smart!”                                                                                                                                    main.py:191
[23:05:48] INFO     Retrying in 2.0 seconds…                                                                                                                             common.py:22
[23:05:50] INFO     Retrying in 2.0 seconds…                                                                                                                             common.py:22

constant retry for the majority of books. For some reason one of the books i was able to bypass was:
 Book: “Eat More, Live Well” 
 
 While almost every other book causes this retry
