### ISSUE TITLE
object of type 'generator' has no len()

### ISSUE THREAD

**Issue by EGhaed** [NicoWeio/blinkist#33]
Hi,
Thank you for great!

While downloading this German daily Book (03/30/2024), I found this error. Could please help us fix it?
I put this attribute in next attempt.

[01:23:56] INFO     Book: “Das Charisma-Geheimnis”                                                                                       main.py:191
[01:24:43] ERROR    Error downloading “Das Charisma-Geheimnis”: object of type 'generator' has no len()       main.py:93
           INFO     Keeping temporary output directory “das-charisma-geheimnis-de.tmp2”                                 main.py:94
           INFO     Continuing with next book… (--continue-on-error was set)                                                      main.py:97
Downloading audio… ⠏ ━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━━━━━━━━━  5/12 0:00:55

Thank you.

**Comment by EGhaed** [comment]
Traceback (most recent call last):
  File "D:\Blinkist\blinkist\main.py", line 200, in <module>
    main()
  File "C:\Users\Esmaeil\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Esmaeil\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Esmaeil\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Esmaeil\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Blinkist\blinkist\main.py", line 193, in main
    download_book(
  File "D:\Blinkist\blinkist\main.py", line 80, in download_book
    chapter.download_audio(book_tmp_dir)
  File "D:\Blinkist\blinkist\blinkist\chapter.py", line 34, in download_audio
    download(self.data['signed_audio_url'], file_path)
  File "D:\Blinkist\blinkist\blinkist\common.py", line 77, in download
    for data in track(
  File "D:\Blinkist\blinkist\blinkist\console.py", line 21, in track
    my_job = _job_progress.add_task(description, total=(total or len(iterable)))
                                                                 ^^^^^^^^^^^^^

**Comment by NicoWeio** [comment]
Curious, will check in a few days. Feel free to ping me if I don't.

**Comment by EGhaed** [comment]
Hi
As you saw the progress bar stopped at chapter five with below content and when I tried to download voice of chapter manually with download manager, a 2KB file with no sound, was the result. I have attached it.
Thank you.

## Blink 5 - Zitat aus dem Buch
<p><em>„Sprich mit den Menschen über sie selbst, und sie werden dir stundenlang zuhören“ – Benjamin Disraeli</em></p>

[05.zip](https://github.com/NicoWeio/blinkist/files/14858689/05.zip)

**Comment by NicoWeio** [comment]
Should be fixed by 987e17d646d90b55e4a44979476291e3a11a25e2. I assume Blinkist changed the way they host audio files, so the _Content-Length_ wasn't known.

Please let me know if the issue persists.
